apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app1-storage-pvc
  namespace: default
spec:
  storageClassName: "oci-bv" # Uses OCI Block Volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # OCI minimum size
