apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-web-app2
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: oci-web-app2
  template:
    metadata:
      labels:
        app: oci-web-app2
      annotations:
        backup.velero.io/backup-volumes: persistent-storage-volume
    spec:
      # --- START OF SOFT ANTI-AFFINITY ---
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - oci-web-app2
              topologyKey: "kubernetes.io/hostname"
      # --- END OF SOFT ANTI-AFFINITY ---
    spec:
      containers:
      - name: web-app2
        # I kept the newer tag (18acda...) - delete the markers!
        image: docker.io/wakeel532687/oci-web-app2:c6f9bfb3fc36f7d5bf1f675860231aea03cc39ba
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: persistent-storage-volume
          mountPath: /app2/data 
      volumes:
      - name: persistent-storage-volume
        persistentVolumeClaim:
          claimName: app2-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oci-web-service2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: oci-web-app2
