apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oci-web-app
  template:
    metadata:
      labels:
        app: oci-web-app
    spec:
      containers:
      - name: web-app
        # Replace with your actual OCIR path
        image: wakeel532687/oci-web-app:5d21f5b7b13df139ba52769eb9cc409b7aba8b76
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: oci-web-service
  annotations:
    # Use your Public Subnet OCID from earlier
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.me-riyadh-1.aaaaaaaaypjbhxx5cqmajclwiw542iswkhmhnq4krzylvcv2uk4t5r3parda"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: oci-web-app
