apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oci-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "oci-app.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oci-web-service # Must match your Service name
            port:
              number: 5000       # Must match your Service port
